### ISSUE TITLE
Bundle codes on skipper-go

### ISSUE THREAD

**Issue by yanrising** [skip-mev/skipper#22]
Hi! I can't figure out what the problem is. Please help me understand

Arbitrage opportunity found:
WEVMOS (0xD4949664cD82660AaE99bEdc034a0deA8A0bd517) to ceUSDC (0xe46910336479F254723710D57e7b683F3315b22B) on Diffusion / ceUSDC (0xe46910336479F254723710D57e7b683F3315b22B) to ceWETH (0x153A59d48AcEAbedbDCf7a13F67Ae52b434B810B) on cronus / ceWETH (0x153A59d48AcEAbedbDCf7a13F67Ae52b434B810B) to WEVMOS (0xD4949664cD82660AaE99bEdc034a0deA8A0bd517) on Diffusion
Amount In: 2.1973025972871232 WEVMOS
Amount Out: 2.290327047821797429 WEVMOS
Profit: 0.093024450534674229 WEVMOS
Bid: 46512225267337114
Bundle Status Code: 4
&{0 4 3 12335887 Don't have skip validator up next <nil> <nil> false <nil> false}
Target TX: https://escan.live/tx/0xc3bb526c35870f2a30ccbcb2dc7aecb32784282d9411507c282785883dd780c9

Arbitrage opportunity found:
WEVMOS (0xD4949664cD82660AaE99bEdc034a0deA8A0bd517) to ceUSDC (0xe46910336479F254723710D57e7b683F3315b22B) on Diffusion / ceUSDC (0xe46910336479F254723710D57e7b683F3315b22B) to ceWETH (0x153A59d48AcEAbedbDCf7a13F67Ae52b434B810B) on cronus / ceWETH (0x153A59d48AcEAbedbDCf7a13F67Ae52b434B810B) to WEVMOS (0xD4949664cD82660AaE99bEdc034a0deA8A0bd517) on Diffusion
Amount In: 2.539842328606928182 WEVMOS
Amount Out: 2.662634960096658249 WEVMOS
Profit: 0.122792631489730067 WEVMOS
Bid: 61396315744865033
Bundle Status Code: 5
&{0 5 3 12335932 BUNDLE REJECTED (failed CheckTx): responses... [code:3 log:"invalid nonce; got 24039, expected 24040: invalid sequence" gas_wanted:3000000 codespace:"sdk"  code:3 log:"invalid nonce; got 3, expected 4: invalid sequence" gas_wanted:400000 codespace:"sdk"  code:4 log:"signature verification failed; please verify account number (19428303) and chain-id (evmos_9001-2): unauthorized" gas_wanted:5000000 gas_used:88317 codespace:"sdk"  ] [map[code:3 codespace:sdk data:<nil> events:[] gas_used:0 gas_wanted:3000000 info: log:invalid nonce; got 24039, expected 24040: invalid sequence mempoolError: priority:0 sender:] map[code:3 codespace:sdk data:<nil> events:[] gas_used:0 gas_wanted:400000 info: log:invalid nonce; got 3, expected 4: invalid sequence mempoolError: priority:0 sender:] map[code:4 codespace:sdk data:<nil> events:[] gas_used:88317 gas_wanted:5000000 info: log:signature verification failed; please verify account number (19428303) and chain-id (evmos_9001-2): unauthorized mempoolError: priority:0 sender:] map[code:0 codespace: data:<nil> events:[] gas_used:0 gas_wanted:0 info: log: mempoolError: priority:0 sender:]] <nil> false [3e5dd57dca8c2dbd235e64720019b644dd67ec89bcf48464d3562795e8caef86 6e248d5e924abea6af807a59e882fb56e1c4764d40af5a60a573e63aad5c77ce 1024e9cf383ef66d36e7bbe2f892c050488d17acc498c644399d23028634e40c] false}
Target TX: https://escan.live/tx/0xce1ce76c75637960aafa39ec390064f99c03e77f9fc201b2f39f43f056004d5c

**Comment by NotJeremyLiu** [comment]
In general, you can find more information on bundle error code responses here: https://docs.skip.money/searcher#-codes-and-meaning

When you see error-code 4, this just means a skip val is not up for when you wanted to include your bundle.

The error code 3 is likely that the target transaction already got included in a block before the auction height you desired. This can happen often due to latency (are you running your own local node?).

Error code 5 is some sig verification error on the tx, curious if it lands on chain properly or not if submitted to mempool... Can you try this?

**Comment by NotJeremyLiu** [comment]
@yanrising I think we've identified a bug on our side that is resulting in these errors when they shouldn't be. Will keep you in the loop on resolution.

**Comment by yanrising** [comment]
The error code 3 - That's what I thought. No, not until I have my own node. It will be necessary to make.
