### ISSUE TITLE
JunoSwap migration to WYND

### ISSUE THREAD

**Issue by TrevorJTClarke** [skip-mev/skipper#9]
Here's the full scope: https://twitter.com/wynddao/status/1613146949276037126?s=20&t=0x_G6NRlQUVH4A3a5OGDbA

likely the junoswap pool files will need shifting when its done

**Comment by NotJeremyLiu** [comment]
@TrevorJTClarke Thank you for opening up this issue! Yes, many of the pools in the contract file currently can't even be swapped against for the freeze. I would like to let searchers integrate this themselves for a bit to reward searchers who are active, but plan to integrate wyndao pools back into the example bot at a later date

**Comment by NotJeremyLiu** [comment]
Migration complete in f63da3883401a03a2be60c970f08534aa5d4f68d

Closing
